"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _main_dashboard from './main-dashboard.bones.json'
import _billing_ops_table from './billing-ops-table.bones.json'
import _contacts_list from './contacts-list.bones.json'

registerBones({
  "main-dashboard": _main_dashboard,
  "billing-ops-table": _billing_ops_table,
  "contacts-list": _contacts_list,
})
